/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Health */
    get: operations['health_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/candles': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Candles
     * @description Candles ordered ascending; paginate backwards with ``end`` or forwards with ``start``.
     */
    get: operations['get_candles_api_v1_candles_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/symbols': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Symbols */
    get: operations['get_symbols_api_v1_symbols_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/funding': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Funding */
    get: operations['get_funding_api_v1_funding_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/open-interest': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Open Interest */
    get: operations['get_open_interest_api_v1_open_interest_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/ticker-summary': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Ticker Summary */
    get: operations['get_ticker_summary_api_v1_ticker_summary_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** CandleOut */
    CandleOut: {
      /**
       * Open Time
       * Format: date-time
       */
      open_time: string
      /** Open */
      open: number
      /** High */
      high: number
      /** Low */
      low: number
      /** Close */
      close: number
      /** Volume */
      volume: number
      /** Quote Volume */
      quote_volume: number
      /** Trades */
      trades: number
      /** Taker Buy Volume */
      taker_buy_volume: number
    }
    /** CandlesResponse */
    CandlesResponse: {
      /** Symbol */
      symbol: string
      /** Interval */
      interval: string
      /** Candles */
      candles: components['schemas']['CandleOut'][]
    }
    /** FundingOut */
    FundingOut: {
      /**
       * Funding Time
       * Format: date-time
       */
      funding_time: string
      /** Rate */
      rate: number
    }
    /** FundingResponse */
    FundingResponse: {
      /** Symbol */
      symbol: string
      /** Entries */
      entries: components['schemas']['FundingOut'][]
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /** OpenInterestOut */
    OpenInterestOut: {
      /**
       * Ts
       * Format: date-time
       */
      ts: string
      /** Oi */
      oi: number
      /** Oi Value */
      oi_value: number
    }
    /** OpenInterestResponse */
    OpenInterestResponse: {
      /** Symbol */
      symbol: string
      /** Entries */
      entries: components['schemas']['OpenInterestOut'][]
    }
    /** SymbolsResponse */
    SymbolsResponse: {
      /** Watchlist */
      watchlist: string[]
      /** Available */
      available: string[]
    }
    /** TickerSummary */
    TickerSummary: {
      /** Symbol */
      symbol: string
      /** Last Price */
      last_price: number | null
      /** Change 24H Pct */
      change_24h_pct: number | null
      /** Volume 24H */
      volume_24h: number | null
      /** Quote Volume 24H */
      quote_volume_24h: number | null
      /** Funding Rate */
      funding_rate: number | null
      /** Oi Change 24H Pct */
      oi_change_24h_pct: number | null
    }
    /** TickerSummaryResponse */
    TickerSummaryResponse: {
      /** Tickers */
      tickers: components['schemas']['TickerSummary'][]
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
      /** Input */
      input?: unknown
      /** Context */
      ctx?: Record<string, never>
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  health_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: string
          }
        }
      }
    }
  }
  get_candles_api_v1_candles_get: {
    parameters: {
      query: {
        symbol: string
        interval?: string
        start?: string | null
        end?: string | null
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CandlesResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_symbols_api_v1_symbols_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SymbolsResponse']
        }
      }
    }
  }
  get_funding_api_v1_funding_get: {
    parameters: {
      query: {
        symbol: string
        start?: string | null
        end?: string | null
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['FundingResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_open_interest_api_v1_open_interest_get: {
    parameters: {
      query: {
        symbol: string
        start?: string | null
        end?: string | null
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['OpenInterestResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_ticker_summary_api_v1_ticker_summary_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TickerSummaryResponse']
        }
      }
    }
  }
}
